update tools

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,35 +6,24 @@ on:
     types: [ opened, synchronize, reopened, ready_for_review ]
 
 jobs:
-  linters:
+  lint:
+    name: Lint
     runs-on: ubuntu-latest
-
     steps:
-      - name: Check out Git repository
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.11"
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
 
-      - name: Install Python dependencies
-        run: pip install ".[dev]"
+      - name: Install pre-commit
+        run: uv tool install pre-commit --with pre-commit-uv --force-reinstall
 
-      - name: Run Black
-        run: black --check src tests
-
-      - name: Run isort
-        run: isort src tests -c
-
-      - name: Run flake8
-        run: flake8 src tests
-
-      - name: Run mypy
-        run: mypy src tests
+      - name: Run pre-commit
+        run: uvx pre-commit run --all-files
 
   build:
-    needs: linters
+    needs: lint
+    name: Build
     runs-on: ubuntu-latest
     outputs:
       WHL: ${{ steps.filenames.outputs.WHL }}
@@ -42,23 +31,22 @@ jobs:
 
     steps:
       - name: Check out Git repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.11"
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
+      - run: uv venv
 
       - name: Setup hatch
-        run: python -m pip install hatch
+        run: uv pip install hatch
 
       - name: Set new version
         if: startsWith(github.ref, 'refs/tags/v')
         run: |
-          python -m hatch version ${GITHUB_REF/refs\/tags\/v/}
+          uv run hatch version ${GITHUB_REF/refs\/tags\/v/}
 
       - name: Build package
-        run: python -m hatch build
+        run: uv build
 
       - name: Set filenames in output
         id: filenames
@@ -67,7 +55,7 @@ jobs:
           echo TARGZ=$(echo dist/*.tar.gz) >> $GITHUB_OUTPUT
 
       - name: Archive package
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: distributions
           path: dist
@@ -75,9 +63,11 @@ jobs:
 
   tests:
     needs: build
+    name: Tests
 
     strategy:
       matrix:
+        python-version: [ "3.11", "3.12", "3.13" ]
         os: [ ubuntu-latest, windows-latest, macos-latest ]
         distribution: [ "${{ needs.build.outputs.WHL }}",
                         "${{ needs.build.outputs.TARGZ }}" ]
@@ -85,21 +75,56 @@ jobs:
 
     steps:
       - name: Check out Git repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
         with:
-          python-version: "3.11"
+          python-version: ${{ matrix.python-version }}
+      - run: uv venv
 
       - name: Download Artifact
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           name: distributions
           path: dist
 
-      - name: Install Python dependencies
-        run: pip install ${{ matrix.distribution }}[test]
+      - name: Install package
+        run: uv pip install ${{ matrix.distribution }}
+
+      - name: Install test dependencies
+        run: uv sync --group test --frozen
+
+      - name: Detect suffix on ubuntu
+        if: ${{ matrix.os == 'ubuntu-latest' or matrix.os == 'macos-latest' }}
+        run: |
+          echo SUFFIX=$(python -c "import pathlib;p=pathlib.Path('${{ matrix.distribution }}');print('whl') if p.suffix=='.whl' else print('tar_gz')") >> $GITHUB_ENV
+
+      - name: Detect suffix on windows
+        if: ${{ matrix.os == 'windows-latest' }}
+        # https://github.com/actions/runner-images/issues/5251#issuecomment-1071030822
+        run: |
+          echo SUFFIX=$(python -c "import pathlib;p=pathlib.Path('${{ matrix.distribution }}');print('whl') if p.suffix=='.whl' else print('tar_gz')") | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
 
       - name: Run pytest
-        run: pytest
+        run: >-
+          uv run pytest
+          --html=pytest_reports/unittest_report_${{ matrix.os }}_py${{ matrix.python-version }}_${{ env.SUFFIX }}.html
+          --self-contained-html
+          --log-file pytest_${{ matrix.os }}_py${{ matrix.python-version }}_${{ env.SUFFIX }}.log
+
+      - name: Archive test result
+        uses: actions/upload-artifact@v4
+        if: success() || failure()  # upload artifacts also if test stage failed
+        with:
+          name: unittest_reports-${{ matrix.os }}-py${{ matrix.python-version }}-${{ env.SUFFIX }}
+          path: pytest_reports/unittest_report_${{ matrix.os }}_py${{ matrix.python-version }}_${{ env.SUFFIX }}.html
+          retention-days: 5
+
+      - name: Archive test log
+        uses: actions/upload-artifact@v4
+        if: success() || failure()  # upload artifacts also if test stage failed
+        with:
+          name: pytest_logs-${{ matrix.os }}-py${{ matrix.python-version }}-${{ env.SUFFIX }}
+          path: pytest_${{ matrix.os }}_py${{ matrix.python-version }}_${{ env.SUFFIX }}.log
+          retention-days: 5
